server {
  listen 4300;
  port_in_redirect off;
  root /usr/share/nginx/html;

  location / {
    try_files $uri $uri/ $uri$args $uri$args /index.html =404;
  }

  location /keller-backend {
    proxy_hide_header Access-Control-Allow-Origin;
    proxy_hide_header Access-Control-Allow-Credentials;
    if ($request_method = "OPTIONS") {
      add_header "Access-Control-Allow-Origin" $http_origin always;
      add_header "Access-Control-Allow-Credentials" "true" always;
      add_header "Access-Control-Allow-Methods" "GET, POST, PUT, DELETE, OPTIONS" always;
      add_header "Access-Control-Allow-Headers" "Content-Type, Authorization" always;
      return 204;
    }
    add_header "Access-Control-Allow-Origin" $http_origin always;
    add_header "Access-Control-Allow-Credentials" "true" always;
    proxy_max_temp_file_size 0m;
    rewrite ^/keller-backend/(.*)$ /$1 break;
    rewrite ^/keller-backend$ / break;
    proxy_pass http://olconet:3000;
  }

  sendfile on;
  client_max_body_size 20M;
  default_type application/octet-stream;

}
